NameError: Replace kcal to kcal_mol-1
Fix issue #461
NameError in the convertor function - utils.py
All the hard coded value are perfectly fine. Here only kcal is changed to kcal_mol-1. For more info refer to http://web.utk.edu/%7Ercompton/constants